DROP TABLE IF EXISTS "User";
DROP TABLE IF EXISTS "Event";
DROP TABLE IF EXISTS "Comment";
DROP TABLE IF EXISTS "Admin";


CREATE TABLE "User"
(
	User_Id SERIAL PRIMARY KEY,
	Name CHARACTER VARYING(128),
	Password CHARACTER VARYING(64),
	Email CHARACTER VARYING(64)
);

CREATE TABLE "Event"
(
	Event_Id SERIAL PRIMARY KEY,
	Author_Id INTEGER,
	Date TIMESTAMP,
	Title CHARACTER VARYING(64),
	Text CHARACTER VARYING(1024),
	Is_Approved BOOLEAN
);

CREATE TABLE "Comment"
(
	Comment_Id SERIAL PRIMARY KEY,
	Event_Id INTEGER,
	Author_ID INTEGER,
	Date TIMESTAMP,
	Text CHARACTER VARYING(256)
);

CREATE TABLE "Admin"
(
	Admin_Id SERIAL PRIMARY KEY,
	Name CHARACTER VARYING(64),
	Password CHARACTER VARYING(64)
);